[package]
name = "volt"
version = "0.1.0"
edition = "2021"

[features]
wayland = []
x11 = []

[dependencies]
anyhow = "1.0.80"
pollster = "0.3.0"
wgpu = "0.19.1"
winit = "0.29.10"
vello = { git = "https://github.com/linebender/vello" }
